{
 "title": "Udacity Metrics - Dashbord1",
 "description": "Dashboard for official Prometheus Python Client's metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "pod",
    "label": "Pod name",
    "query": {
     "query": "label_values(app_version_info, pod)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(app_request_latency_seconds_bucket, exported_endpoint)"
    }
   },
   {
    "name": "method",
    "label": "HTTP Method",
    "query": {
     "query": "label_values(app_request_latency_seconds_bucket, method)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": "100,99,95,90,75,50,25" },
   {
    "name": "error_code",
    "label": "Status code 4xx or 5xx",
    "query": {
     "query": "label_values(app_request_count_total, http_status)"
    }
   },
   {
    "name": "service",
    "label": "Service name",
    "query": {
     "query": "label_values(app_version_info, service)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "4xx, 5xx errors count backend",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "app_request_count_total{http_status=~\"$error_code\", service=~\"backend-service\", method=~\"$method\", exported_endpoint=~\"$endpoint\"}",
     "legendFormat": "{{ http_status }} {{ service }} {{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors count frontend",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "app_request_count_total{http_status=~\"$error_code\", service=~\"frontend-service\", method=~\"$method\", exported_endpoint=~\"$endpoint\"}",
     "legendFormat": "{{ http_status }} {{ service }} {{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Service uptime by second",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{service=~\"backend-service\"})",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "HTTP Request by second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "rate(app_request_count_total{service=~\"$service\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$interval])",
     "legendFormat": "{{ service }} - {{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Service uptime by second",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{service=~\"frontend-service\"})",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(avg by (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|steal\", cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"$cluster\"}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 30 },
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container!=\"\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}